### ISSUE TITLE
iothub-explorer get --connection-string <device> results in an exception

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdks#1004]
When I tried to get the connection string of a device following error occurred:

```
# iothub-explorer get cclu-0001 --connection-string
/usr/lib64/node_modules/iothub-explorer/common.js:22
  if (deviceInfo.authentication.SymmetricKey.primaryKey) {
                                            ^

TypeError: Cannot read property 'primaryKey' of undefined
    at createDeviceConnectionString (/usr/lib64/node_modules/iothub-explorer/common.js:22:45)
    at printDevice (/usr/lib64/node_modules/iothub-explorer/common.js:135:31)
    at /usr/lib64/node_modules/iothub-explorer/iothub-explorer-get.js:33:5
    at /usr/lib64/node_modules/iothub-explorer/node_modules/azure-iothub/lib/registry.js:223:7
    at /usr/lib64/node_modules/iothub-explorer/node_modules/azure-iothub/lib/rest_api_client.js:109:7
    at IncomingMessage.onResponseEnd (/usr/lib64/node_modules/iothub-explorer/node_modules/azure-iot-http-base/lib/http.js:73:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

It seems that the variable is actually symmetricKey instead of SymmetricKey. By replacing the respective instances I was able to run the program correctly. I'll attach a patch.

[fix_connection_string_calculation.txt](https://github.com/Azure/azure-iot-sdks/files/623961/fix_connection_string_calculation.txt)

**Comment by sebastian-azeti** [comment]
Check #998 seems like you ran into the same problem. I tested it today and the fix from the guys works fine. Just install the latest `npm install -g iothub-explorer@latest`

**Comment by czyba** [comment]
Ahh, works, great. It seems I missed the release by a couple of hours. Thanks
