### ISSUE TITLE
iothub-explorer error: "The connection string is missing the property: SharedAccessKeyName"

### ISSUE THREAD

**Issue by karolkulesza** [Azure/azure-iot-sdks#1049]
Hi there,

After installing `iothub-explorer` tool on OS X (iothub-explorer v.1.1.3, OS X v.10.11.6), I'm currently unable to perform the following invocation:

`iothub-explorer login HostName=(...).azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=(...) `

Command line invocation throws the following error:

```
/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iot-common/lib/connection_string.js:21
    if (!(key in dict)) throw new ArgumentError(err + key);
                              ^
ArgumentError: The connection string is missing the property: SharedAccessKeyName
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iot-common/lib/connection_string.js:21:31
    at Array.forEach (native)
    at Function.parse (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iot-common/lib/connection_string.js:20:18)
    at Object.parse (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/connection_string.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/iothub-explorer/iothub-explorer-login.js:33:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

As you can see, the `SharedAccessKeyName` property IS available in the connection string.

Best Regards,
Karol

**Comment by karolkulesza** [comment]
Fixed. Invalid invocation
