### ISSUE TITLE
Null Thrown From AMQP10 Library

### ISSUE THREAD

**Issue by kranthisai** [Azure/azure-iot-sdks#1053]
Got the following error while subscribing to the evnts from Azure 

Logs:
/home/kranthi/workspace/axon-winjit-bridge/node_modules/amqp10/lib/frames.js:54
  stream.write(buffer);
        ^

TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/home/kranthi/workspace/bridge/node_modules/amqp10/lib/frames.js:54:9)
    at Connection.sendFrame (/home/kranthi/workspace/bridge/node_modules/amqp10/lib/connection.js:333:10)
    at ReceiverLink.Link.attach (/home/kranthi/workspace/bridge/node_modules/amqp10/lib/link.js:108:27)
    at ReceiverLink.Link._attemptReattach (/home/kranthi/workspace/bridge/node_modules/amqp10/lib/link.js:237:8)
    at Timeout._onTimeout (/home/kranthi/workspace/bridge/node_modules/amqp10/lib/link.js:225:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

 used libraries: ('azure-event-hubs').Client;

This issue is not caused all the time. It works good other times. seeing this issue for the past two days..

SDK Useed: Node,
version: "azure-event-hubs": "0.0.4",
code snippet:

test.js

const printError = function (err) {
    console.log(err.message);
};

const printMessage = function (message) {
    console.log('Message received: ');
    console.log(JSON.stringify(message.body));
    console.log('');
};
const client = EventHubClient.fromConnectionString(connectionString);
client.open()
    .then(client.getPartitionIds.bind(client))
    .then(function (partitionIds) {
        return partitionIds.map(function (partitionId) {
            return client.createReceiver('$Default', partitionId, { 'startAfterTime' : Date.now()}).then(function(receiver) {
                console.log('Created partition receiver: ' + partitionId);
                receiver.on('errorReceived', printError);
                receiver.on('message', printMessage);
            });
        });
    })
    .catch(err1 => {
        console.log("got errror");
        printError(err1);
    }).catch(err => {
        console.log("got Error");
        printError(err);
});

**Comment by kranthisai** [comment]
I resolved the issue.

process.on('uncaughtException', err => {
console.log('Caught exception: ', err);
});

It will not terminate the app. Will wait for connection to establish..
