### ISSUE TITLE
Iothub-explorer.js reported error with AMQP 

### ISSUE THREAD

**Issue by NNM11** [Azure/azure-iot-sdks#185]
I ran the iothub-explorer tool successfully before to monitor events for registered devices with IotHub.  Today, I just got an error with AMQP reported back.  Any idea what is wrong?  This used to work.

- Set 2 environment variables IOTHUB_CONNSTR (SAS from an Azure IoTHub) and IOTHUB_DEVID (device unique ID)

-  run the tool as:

`
root@Device:/home/gwuser/azure-solution# node ./tools/iothub-explorer.js $IOTHUB_CONNSTR monitor-events $IOTHUB_DEVID
Monitoring events from device XXXXXXXXXX
Unhandled rejection Error: error receiving reply from Event Hub management endpoint: An AMQP error occurred (condition='amqp:link:redirect').
    at ReceiverLink.<anonymous> (/home/gwuser/azure-solution/tools/lib/eventhubclient.js:81:22)
    at emitOne (events.js:82:20)
    at ReceiverLink.emit (events.js:169:7)
    at ReceiverLink.Link._detached (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/link.js:176:10)
    at ReceiverLink.Link._detachReceived (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/link.js:161:8)
    at Session._processDetachFrame (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/session.js:343:45)
    at Session._processFrame (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/session.js:310:35)
    at Connection._processFrameEH (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/session.js:194:49)
    at emitOne (events.js:82:20)
    at Connection.emit (events.js:169:7)
    at Connection._receiveAny (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/connection.js:447:16)
    at Connection._receiveData (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/connection.js:364:8)
    at null.<anonymous> (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/connection.js:536:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at TLSSocket.<anonymous> (/home/gwuser/azure-solution/tools/node_modules/amqp10/lib/transport/tls_transport.js:28:48)`

**Comment by damonbarry** [comment]
There was a version update last week to the AMQP library we depend on (amqp10).  We're accessing some private stuff in that library which changed, as private stuff is wont to do.  So our library broke.

On 12/4/2015 we published a new version of our packages (v1.0.0-preview.8) which lock down our amqp10 dependency at 2.1.2 so we don't run into this problem.  You can also get the latest packages by pulling our master branch.

In the meantime, we'll be updating our code so we can handle newer versions of amqp10.

**Comment by NNM11** [comment]
Hi Damon,

Is the latest release 2015-12-17 had this fix?   I just pulled the master branch and build the node sdk.  The build/build.sh test return 4 test failures (attached file).

Thanks,

._.  Nghia
