### ISSUE TITLE
Object prototype may only be an Object or null

### ISSUE THREAD

**Issue by fotoKrille** [Azure/azure-iot-sdks#211]
Using Node v0.10.40 on MAC

util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:556:27)
    at Object.<anonymous> (/Users/fotoKrille/Documents/GitHub/node_modules/azure-iot-device/node_modules/azure-iot-common/lib/amqp_receiver.js:43:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/fotoKrille/Documents/GitHub/node_modules/azure-iot-device/node_modules/azure-iot-common/common.js:16:19)

**Comment by fotoKrille** [comment]
Update node to v0.12.9

**Comment by gurtaj** [comment]
Hi. I am trying to install iot hub explorer on my Raspberry Pi using the following
<img width="641" alt="screen shot 2016-07-20 at 6 11 32 pm" src="https://cloud.githubusercontent.com/assets/20566866/17004947/83f64fe6-4ea5-11e6-9374-132427c59ebc.png">


but as soon as I try to register my device using the command 
iothub-explorer <iothub-connection-string> create <device-name> --connection-string
, it gives me the following error
<img width="641" alt="screen shot 2016-07-20 at 6 19 30 pm" src="https://cloud.githubusercontent.com/assets/20566866/17005133/926de024-4ea6-11e6-94d0-201c40a36f20.png">
