### ISSUE TITLE
SDK Build fails when using Gradle instead of Maven

### ISSUE THREAD

**Issue by rgknp** [Azure/azure-iot-sdks#213]
Java SDK build fails when built using Gradle. Gradle is another build tool just like Maven which is quite popular among Java developers.

<project root>\azure-iot-sdks\java\device>gradle build
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:iothub-java-client:compileJava UP-TO-DATE
:iothub-java-client:processResources UP-TO-DATE
:iothub-java-client:classes UP-TO-DATE
:iothub-java-client:jar UP-TO-DATE
:iothub-java-client:assemble UP-TO-DATE
:iothub-java-client:compileTestJava UP-TO-DATE
:iothub-java-client:processTestResources UP-TO-DATE
:iothub-java-client:testClasses UP-TO-DATE
:iothub-java-client:test

tests.unit.com.microsoft.azure.iothub.auth.SignatureHelperTest > encodeSignatureEscapesWithUtf8Charset FAILED
    java.lang.AssertionError at SignatureHelperTest.java:108

tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest > openTriggersReactorAndOpensConnection FAILED
    mockit.internal.MissingInvocation at AmqpsIotHubConnectionTest.java:300
        Caused by: mockit.internal.expectations.invocation.ExpectationError at AmqpsIotHubConnectionTest.java:300

415 tests completed, 2 failed
:iothub-java-client:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iothub-java-client:test'.
> There were failing tests. See the report at: file:///<project root>/azure-iot-sdks/java/device/iothub-java-client/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Details of failure:

encodeSignatureEscapesWithUtf8Charset
java.lang.AssertionError: 
Expected: is ("%C3%BCm%40%3F" or "%c3%BCm%40%3f")
     but: was "%C3%83%C2%BCm%40%3F"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at tests.unit.com.microsoft.azure.iothub.auth.SignatureHelperTest.encodeSignatureEscapesWithUtf8Charset(SignatureHelperTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Wrap lines 

openTriggersReactorAndOpensConnection
mockit.internal.MissingInvocation: Missing 1 invocation to:
org.apache.qpid.proton.reactor.Reactor#run()
   on mock instance: org.apache.qpid.proton.reactor.$Impl_Reactor@37de6f7c
	at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest$12.<init>(AmqpsIotHubConnectionTest.java:302)
	at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersReactorAndOpensConnection(AmqpsIotHubConnectionTest.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Missing invocations
	... 23 more

**Comment by tameraw** [comment]
@rgknp - Thanks for providing us with this info. We have added this to our backlog.

**Comment by tameraw** [comment]
Closing as this has been captured in our product backlog for future support.
