### ISSUE TITLE
Error using iothub-explorer tool

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#250]
I installed the tool in a Linux environment using:

```
npm install -g iothub-explorer@latest
```

Then trying to use the **send** command I see:

```
dominicbetts:~/workspace $ iothub-explorer send myFirstDevice AMessage
/home/ubuntu/.nvm/versions/node/v0.12.9/lib/node_modules/iothub-explorer/node_modules/azure-iothub/node_modules/azure-iot-amqp-base/lib/amqp.js:53
  if (this.uri.startsWith('wss')) {
               ^
TypeError: undefined is not a function
    at new Amqp (/home/ubuntu/.nvm/versions/node/v0.12.9/lib/node_modules/iothub-explorer/node_modules/azure-iothub/node_modules/azure-iot-amqp-base/lib/amqp.js:53:16)
    at new Amqp (/home/ubuntu/.nvm/versions/node/v0.12.9/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/amqp.js:30:16)
    at Function.fromSharedAccessSignature (/home/ubuntu/.nvm/versions/node/v0.12.9/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/client.js:93:21)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v0.12.9/lib/node_modules/iothub-explorer/iothub-explorer.js:230:108)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by cwrenniks** [comment]
What version of npm are you using?

**Comment by dominicbetts** [comment]
dominicbetts:~/workspace $ npm --version
2.14.9

**Comment by pierreca** [comment]
I think startsWith() is a method that was introduced later, and does not exist in older node versions (0.12...). It's on us to either change that code to make it compatible with 0.12.x versions or end support for this version.
May I ask, is that the default version on your machine? because it's an old one, the LTS 4.2.6 and the latest is 5.5.0... is there a more recent package for your distribution?

**Comment by dominicbetts** [comment]
I have Node 0.12.9 installed on the machine. I'll try upgrading to a later version.

**Comment by dominicbetts** [comment]
I tried with Node 4.2.6 and it works fine. I guess this means that Node 4.* or higher is a prerequisite for this tool?

**Comment by pierreca** [comment]
Looks like it. I'll update the package.json file

**Comment by cwrenniks** [comment]
Be careful, as I ran into something similar with a newer version of NPM ( newer than what is in the standard Node.js distro ). Damon is aware.

**Comment by tameraw** [comment]
@dominicbetts - Thanks for noting this.
I'm closing this issue as I see that you have already updated the readme file to reflect that Node 4.* or higher is a prerequisite for this tool. Thanks.
