### ISSUE TITLE
Problem using azure-iot-sdk for node.js with node.js version 4.x

### ISSUE THREAD

**Issue by JakobBlomberg** [Azure/azure-iot-sdks#256]
I'm trying to setup a connection to a IoT Hub using the sdk for node.js. I already have node.js code that requires at least node.js version 4.x but when I try to execute my node app I get the following error:

c:\src2\node_modules\azure-iot-device\lib\client.js:39
  if (!value) throw new ReferenceError('value is \'' + value + '\'');
              ^

ReferenceError: value is ''
    at Function.fromConnectionString (c:\src2\node_modules\azure-iot-device\lib\client.js:39:21)
    at module.exports.clientFromConnectionString (c:\src2\node_modules\azure-iot-device-amqp\index.js:12:26)
    at new ZwaveServer (c:\src2\zwaveAdapter.js:242:28)
    at Object.<anonymous> (c:\src2\server.js:23:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

If I use the 0.12.x version of node.js then I don't get these errors but my existing node.js code do not work + the 0.12.x version is really old.

**Comment by JakobBlomberg** [comment]
User stupidity!

Solved the issue, the IoT Hub connection string was not formatted correctly but it looked like the lib wasn't loaded correctly.
