### ISSUE TITLE
Node Build Failure

### ISSUE THREAD

**Issue by careybd** [Azure/azure-iot-sdks#265]
Hello,
I'm trying to compile the updated node SDK for linux, however I'm getting failures when running build.sh after running dev-setup.sh per the directions. When executing the script ../azure-iot-sdks/node/build/build.sh I get the following error:

```../azure-iot-sdks/node/device/transport/amqp
../azure-iot-sdks/node/device/transport/amqp/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
              ^
Error: cannot resolve path (or pattern) 'lib/_*_test.js'
    at Object.lookupFiles (../azure-iot-sdks/node/device/transport/amqp/node_modules/mocha/lib/utils.js:628:15)
    at ../azure-iot-sdks/node/device/transport/amqp/node_modules/mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (../azure-iot-sdks/node/device/transport/amqp/node_modules/mocha/bin/_mocha:325:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I then ran the build.sh script in ../azure-iot-sdks/build/ and got the following:
```
  2 failing

  1) Over AMQP Client #sendEvent sends the event:
     TypeError: undefined is not a function
      at new Amqp (../azure-iot-sdks/node/common/transport/amqp/lib/amqp.js:53:16)
      at new Amqp (lib/amqp.js:31:16)
      at Function.fromConnectionString (../azure-iot-sdks/node/device/core/lib/client.js:54:21)
      at Context.<anonymous> (lib/_client_test_integration.js:77:29)

  2) Over AMQP Client #getReceiver returns the same receiver instance if called multiple times:
     TypeError: undefined is not a function
      at new Amqp (../azure-iot-sdks/node/common/transport/amqp/lib/amqp.js:53:16)
      at new Amqp (lib/amqp.js:31:16)
      at Function.fromConnectionString (../azure-iot-sdks/node/device/core/lib/client.js:54:21)
      at Context.<anonymous> (lib/_client_test_integration.js:97:29)

```

Not sure if it's a mistake on my end but hoping for some help. Thanks

**Comment by pierreca** [comment]
The 2 errors have different causes:
- regarding the 'cannot resolve' error: this is solved in the next release and is due to the absence of test files with the proper naming convention (there are only integration tests for now). you can resolve this by opening [device/transport/amqp/package.json](https://github.com/Azure/azure-iot-sdks/blob/master/node/device/transport/amqp/package.json) file and changing the "unittest" and "unittest-min" commands to "echo \"No tests\"" (as in the [common/https/package.json](https://github.com/Azure/azure-iot-sdks/blob/master/node/common/transport/http/package.json)) file.

- regarding the second error: since these builds run integration tests you need to have the E2E tests environments variables configured as described [here](https://github.com/Azure/azure-iot-sdks/blob/f71ae7abdcefede3fdd9af2c789a687a8caa4627/c/doc/run_end_to_end_tests.md).

Please let us know if this helps!

**Comment by careybd** [comment]
That takes care of it, appreciate the help!
