### ISSUE TITLE
Connection unable to be opened in time (Java)

### ISSUE THREAD

**Issue by MrAGi** [Azure/azure-iot-sdks#266]
Attempting to run the simulated device tutorial application generates the following error:

`java.io.IOException: java.util.concurrent.ExecutionException: java.lang.Throwable: Connection unable to be opened in time.
	at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:88)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:169)
	at com.mycompany.app.App$MessageSender.run(App.java:59)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.Throwable: Connection unable to be opened in time.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.reactorReady(AmqpsIotHubConnection.java:489)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:177)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:86)
	... 3 more
Caused by: java.lang.Throwable: Connection unable to be opened in time.
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$onConnectionLocalOpen$3(AmqpsIotHubConnectionBaseHandler.java:307)
	... 1 more
Error: Error{condition=amqp:connection:framing-error, description='org.apache.qpid.proton.engine.TransportException: connection aborted', info=null}
Error: org.apache.qpid.proton.engine.TransportException: connection aborted`

This issue is also mentioned in the comments on the [tutorial page](https://azure.microsoft.com/en-gb/documentation/articles/iot-hub-java-java-getstarted/).

I have tried both preview 8 and 9 as suggested in the comments.

**Comment by MrAGi** [comment]
If I change:

`private static IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;`

to:

`private static IotHubClientProtocol protocol = IotHubClientProtocol.HTTPS;`

the connection error goes away to be replaced by another message:

`IoT Hub responded to message with status HUB_OR_DEVICE_ID_NOT_FOUND`

**Comment by dominicbetts** [comment]
Can you double check your connection-string? It should look like this:

```
private static String connString = "HostName={youriothubname}.azure-devices.net;DeviceId={yourdeviceid};SharedAccessKey={yourdevicekey}";
```

**Comment by MrAGi** [comment]
`connString` looks fine. I have taken the `deviceId` and `SharedAccessKey` from the output of the first tutorial program (create-device-identity) and the `HostName` matches the one given in the Azure web portal.

**Comment by dominicbetts** [comment]
@tameraw I've run the tutorial code using the following combinations and they all successfully send messages:

- preview9 with AMQPS
- preview8 with AMQPS
- preview9 with HTTPS
- preview8 with HTTPS

The AMQPS tests do show a warning about the bouncycastle provider, but this doesn't stop them from running.

**Comment by MrAGi** [comment]
@dominicbetts @tameraw I think this problem is related to issue #275/#225.

I downloaded the Device Explorer and enabled a device manually and it is connecting now.

I guess I will wait for the new release.

**Comment by dominicbetts** [comment]
Thanks for letting us know!

**Comment by tameraw** [comment]
@MrAGi - Since both related issues were resolved, closing this one as well. Please feel free to reopen if still having issues. Thanks.
