### ISSUE TITLE
azure-iot-device fails on old Nodejs version

### ISSUE THREAD

**Issue by Shachar1** [Azure/azure-iot-sdks#385]
Hi, I've some devices that still have Node v0.10.25, when I run the IoT hub SDK I'm getting: 

Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:555:27)
    at Object.<anonymous> (/node_modules/azure-iot-device/lib/client.js:56:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>

It's working fine on the new Node versions > 5
I will have a problem to update those devices to a newer version so I wanted to know if there is any solution

Thanks

**Comment by pierreca** [comment]
Hi @Shachar1 
support for node 0.10.x has been added to our `develop` branch and will be deployed to npm around the end of this week or beginning of next week. in the meantime, feel free to clone our repository and use the content of the `develop` branch.

Out of curiosity, which devices are you talking about?

**Comment by Shachar1** [comment]
Thanks for the fast replay.
The device is a Field Gateway of a large security company that runs old/costumed Linux distribution which prevent them to install the newer versions of Node.
