### ISSUE TITLE
Connection to IoT Hub using Java Device SDK is disconnected every 20 minutes and reconnects in about one minute

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#459]
with amqps_ws to IoT Hub using Java Device SDK, the connection closed exactly every 20 minutes and reconnectes in about one minute.

**Comment by eissi** [comment]
Exception that occurs every 20 minutes is below.

Exception in thread "Thread-1909" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1916" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1919" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1921" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1923" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1925" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
Exception in thread "Thread-1927" java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.send(SenderImpl.java:47)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseHandler.lambda$1(AmqpsIotHubConnectionBaseHandler.java:490)
	at java.lang.Thread.run(Unknown Source)
Failed to send message because: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
The Amqps Transport crashed. All previously queued messages will be sent again. All unqueued messages will be queued.
java.io.IOException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Throwable: Default timeout exceeded before this message was sent.
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.sendMessages(AmqpsTransport.java:257)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:25)
java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
java.util.concurrent.FutureTask.runAndReset(Unknown Source)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by tameraw** [comment]
@eissi - Thanks for filing this issue. We're investigating.

**Comment by BlueBasher** [comment]
@tameraw I know it's a fairly new issue, but is there any new about it? We're currently also hitting the disconnect after 20 minutes which is obviously causing some problems.

**Comment by iluican** [comment]
This has to do with the token expiration. Currently it's set to 10 minutes. Since the device is not disconnected immediately after the token expires, that's where the 20 minutes come from. This is causing no issue, however, since the connection is re-established automatically and no message is being lost (the messages are being sent when the connection is re-established). I agree that the exception looks ugly and we're working on changing that.

Thank you,
Ilie.

**Comment by BlueBasher** [comment]
If i understand correctly this means that every 20 minutes a reconnect happens, all the time? How does this hold to the bandwidth usage? Connecting is a pretty 'heavy' operation if I'm not mistaken, so for devices that are connected using a mobile network reconnecting every 20 minutes has quite a big impact.

**Comment by iluican** [comment]
We made the token expiration configurable now. Please have a look at TOKEN_VALID_SECS in DeviceClientConfig. You can set it to any value you want, so you can have a reconnect a day or even less. Please let us know if this solves your problem.

Thank you,
Ilie.

**Comment by eissi** [comment]
Thanks Iluican, I will test and get back to you if it works well.

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by eissi** [comment]
Iluican,

I saw the change and I’d like to confirm that you increased the default from 10 minutes to 60 minutes. Right?

And you created the variable but, there is no way to change the value in my code. Rather, I have to change the SDK itself.
Do you have any plan to change the value in my code when I open the DeviceClient instance as my customer doesn’t want to manage another branch from our SDK offering?


감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by iluican** [comment]
You are correct, you cannot change the token expiration currently. We have a bug in our backlog to change that.

Thank you,
Ilie.

**Comment by tameraw** [comment]
Controlling SAS token expiration has been added in the Java SDK. Please let us know if you see any issues.

**Comment by amandeep7** [comment]
I want create SAS token for each device which is conneted to IOT HUB in java.

using this iotHubConnectionString = IotHubConnectionStringBuilder

.createConnectionString("HostName=IotHub.azure-devices.net;DeviceId=DEV001;SharedAccessKeyName=device;SharedAccessKey=ceva7/B9HBs2O9u1QqAGpkFbgyAJ93t0gw+qM/nLstU=);

sas = new IotHubServiceSasToken(iotHubConnectionString);



but by using above sas we can able to send data to IOT HUB.
