### ISSUE TITLE
Getting started with IoT

### ISSUE THREAD

**Issue by OmarHallab** [Azure/azure-iot-sdks#460]
Hello, 

I am currently developing an IoT project on a beagle bone black & using javascript for my programming language. 

I am trying to run this sample code provided by the getting started page :  

```js
// Add reference to the Azure IoT Hub device library
var device = require('azure-iot-device');
// Define the connection string to connect to IoT Hub
var connectionString = '[IoT Device Connection String]';
// Create the client instance specifying the preferred protocol
var client = new device.Client(connectionString, new device.Https());
// Create a message and send it to IoT Hub.
var data = JSON.stringify({ 'deviceId': 'myFirstDevice', 'data': 'mydata' });
var message = new device.Message(data);
message.properties.add('myproperty', 'myvalue');
client.sendEvent(message, function(err, res){
    if (err) console.log('SendEvent error: ' + err.toString());
    if (res) console.log('SendEvent status: ' + res.statusCode + ' ' + res.statusMessage);
});
// Receive messages from IoT Hub
client.receive(function (err, res, msg) {
  console.log('receive data: ' + msg.getData());
  client.complete(msg, function(err, res){
    if (err) console.log('Complete error: ' + err.toString());
    if (res) console.log('Complete status: ' + res.statusCode + ' ' + res.statusMessage);
  });
});
```
-------
But I am getting this error : 

```
var client = new device.Client(connectionString, device.https());
                                                                                  ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/AzureSample/sample.js:5:57)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
--------
Can someone please get back to me on this 
Thank you,
Omar

**Comment by pierreca** [comment]
Hi @OmarHallab 

I think the problem is how the client is instanciated.

You can either use the constructor with a "config" object or use the `Client.fromConnectionString()` method with a connection string. using the `Client()` constructor with a connection string will not work though.

Here's a link to an example: https://github.com/Azure/azure-iot-sdks/blob/master/node/device/samples/simple_sample_device.js#L19

**Comment by OmarHallab** [comment]
Hi @pierreca, 

I have fixed the instance of client by following the simple_sample_device.js repo .. messages are being sent to IoT hub successfully :+1:  .

Thanks,
Omar
