### ISSUE TITLE
DeviceClient.SendEventAsync throws exception when using AMQP on UWP

### ISSUE THREAD

**Issue by locatw** [Azure/azure-iot-sdks#471]
I'm using Microsoft.Azure.Devices.Client version 1.0.5 in VS Community 2015 Update2.

I create UWP project and execute following code on my Windows 10 PC, DeviceClient.SendEventAsync throws ArgumentOutOfRangeException.

    [C#]
    string uri = "<My iot hub uri>";
    string deviceId = "<My device id>";
    string deviceKey = "<My device key>";
    var deviceClient = DeviceClient.Create(
        uri,
        new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, deviceKey),
        TransportType.Amqp);
    
    var message = new Message(Encoding.UTF8.GetBytes("AMQP Test"));
    
    await deviceClient.SendEventAsync(message);

The exception message is:

    The UTC time represented when the offset is applied must be between year 0 and 10,000.
    Parameter name: offset

and stacktrace is:

       at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
       at System.DateTimeOffset..ctor(DateTime dateTime)
       at System.DateTimeOffset.op_Implicit(DateTime dateTime)
       at     Microsoft.Azure.Devices.Client.MessageConverter.UpdateAmqpMessageHeadersAndProperties(AmqpMessage amqpMessage, Message data, Boolean copyUserProperties)
       at Microsoft.Azure.Devices.Client.Message.PopulateAmqpMessageForSend(AmqpMessage message)
       at Microsoft.Azure.Devices.Client.Message.ToAmqpMessage(Boolean setBodyCalled)
       at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnSendEventAsync>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.Azure.Devices.Client.Transport.TransportHandlerBase.<SendEventAsync>d__21.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass32_0.<<SendEventAsync>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at AmqpDesktopTest.MainPage.<SendMessage>d__4.MoveNext()

**Comment by arturl** [comment]
Thanks @tameraw, I'll take a look

**Comment by arturl** [comment]
@locatw, I cannot repro this problem, it could be only reproducible in your local time/locale. I do have a theory though -- do you think you will be able to try out a fix if I give you a change?

**Comment by locatw** [comment]
I apply your experimental fix to MessageConverter, then DeviceClient.SendEvenAsync sent message successfully.

**Comment by arturl** [comment]
Thanks, @locatw!

**Comment by locatw** [comment]
Thank you, too!

**Comment by arturl** [comment]
Fixed by https://github.com/Azure/azure-iot-sdks/commit/4d7649dcd45969120772f1215f58dfddc33d8969
