### ISSUE TITLE
Exception attempting to run Java SDK sample code in enRoute OSGi

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-iot-sdks#483]
Not sure if I'm conflating them, but I am having multiple issues with the Java SDK client.

Scenario: Trying to run the send-receive sample code within enRoute OSGi.

Issue 1: I had to add a dependency on the SDK .jar and import all of the client packages manually.  `com.ibm.mqttdirect.modules.local.bindings` had to be marked as optional.  it's not shipped with the SDK and Bndtools could not resolve the bundle without it. It appears to only be referenced by `org.eclipse.paho.client.mqttv3.internal.NetworkModule` which is included. At any rate, marking it as optional resolves the bundle resolution issue.

Issue 2: The next issue I'm having is that the following exception occurs when device.open() is called. I can't be certain, but I'm assuming that the exception I'm seeing is unrelated to the anomaly above since it's associated some type of parsing of the SAS token. I haven't seen this running the sample code outside of OSGi.

```
Starting...
Beginning setup.
Using communication protocol MQTT.
Successfully created an IoT Hub client.
Successfully set message callback.
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.microsoft.azure.iothub.auth.SignatureHelper.decodeDeviceKeyBase64(SignatureHelper.java:55)
	at com.microsoft.azure.iothub.auth.Signature.<init>(Signature.java:27)
	at com.microsoft.azure.iothub.auth.IotHubSasToken.<init>(IotHubSasToken.java:42)
	at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:123)
	at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.open(MqttTransport.java:87)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:162)
	at com.mesh.lab.mqtt.application.Receive.run(Receive.java:127)
	at com.mesh.lab.mqtt.application.MqttApplication.lambda$0(MqttApplication.java:13)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter cannot be found by com.mesh.lab.mqtt.application_1.0.0.201604140104
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

```

**Comment by bcraun** [comment]
EDIT: I resolved the issue within Bndtools by adding a wildcarded catchall filter in the "Customize Imports" pane. Not sure why that fixed it, but if it helps anyone else...
