### ISSUE TITLE
NodeJS: EventHubClient createReceiver causes exception

### ISSUE THREAD

**Issue by kenr** [Azure/azure-iot-sdks#621]
Using NodeJS API, EventHubClient.createReceiver result in an error:

  outStream.write(buffer);
           ^

TypeError: Cannot read property 'write' of null
    at AttachFrame.Frame.write (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\frames\frame.js:86:12)
    at Connection.sendFrame (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\connection.js:336:9)
    at ReceiverLink.Link.attach (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:101:27)
    at ReceiverLink.Link._attemptReattach (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:204:8)
    at Timeout._onTimeout (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:192:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

I'm not able to get any of the messages put into the IoT Hub by a device (on the service side).

**Comment by pierreca** [comment]
Closing here since it appears to be an event hubs thing. will reopen if it's indeed specific to the iot hub SDK. Investigation will go on at https://github.com/Azure/azure-event-hubs/issues/167
