### ISSUE TITLE
Java SDK Thread stuck in DeviceClient.close() for AMPQSTransport implementation

### ISSUE THREAD

**Issue by oriolpinol** [Azure/azure-iot-sdks#684]
During a reconnect attempt using the java SDK under linux, the thread running got stuck in the close method:

```
"qtp540159270-161" #161 prio=5 os_prio=31 tid=0x00007f98fe2c8000 nid=0x621f runnable [0x00000001270c7000]
   java.lang.Thread.State: RUNNABLE
	at com.microsoft.azure.iothub.DeviceClient.close(DeviceClient.java:201)
	at se.yanzi.shrek.azureiothub.IoTHubSession.disconnect(IoTHubSession.java:218)
	at se.yanzi.shrek.azureiothub.IoTHubSession.stop(IoTHubSession.java:311)
	at se.yanzi.shrek.plugins.IoTHubPlugin.setState(IoTHubPlugin.java:130)
	at se.yanzi.shrek.plugins.IoTHubPlugin.handleMessage(IoTHubPlugin.java:176)
	at se.yanzi.shrek.plugins.IoTHubPlugin.handleMessage(IoTHubPlugin.java:25)
	at se.yanzi.shrek.cirrus.web.ConfigurationServlet.onMessage(ConfigurationServlet.java:57)
	at se.yanzi.shrek.cirrus.web.WebSocketServletTemplate.onMessage(WebSocketServletTemplate.java:46)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
	at org.eclipse.jetty.websocket.jsr356.annotations.OnMessageTextCallable.call(OnMessageTextCallable.java:63)
	at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callText(JsrEvents.java:197)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextMessage(JsrAnnotatedEventDriver.java:378)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:360)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:367)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:176)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

When checking closely at the code this the loop: 

```
        while (!this.transport.isEmpty())
        {

        }
```

Also, checking the AMPQSTransport implementation and comparing it to the MQTTTransport implementation, I observed that the messageSent related operations are synchronized with a (sendMessagesLock) in the MQTT implementation but not in the AMQPS implementation. Could that be the cause of the issue? Is there any reason for that difference?

Thank you very much!

**Comment by jtanner-msft** [comment]
Hi oriolpinol,

  There are some known issues related to reconnection with the Java SDK that we are looking at resolving now.  This issue covers one of the ones that we are looking to resolve soon for example:  https://github.com/Azure/azure-iot-sdks/issues/655.  My hope is that once the overall reconnection issues have been addressed you’ll no longer see your thread get stuck in the close method.

  The reason that the AMQP Transport is not blocking in the same way that the MQTT one is because it uses SocketChannels http://docs.oracle.com/javase/7/docs/api/java/nio/channels/SocketChannel.html  instead of pure sockets.  This discussion discusses the differences between the two implemenations: http://stackoverflow.com/questions/14225957/socket-vs-socketchannel 

  I hope that answers your questions for the moment.  While we don’t have a fix just yet around the reconnect, it is something we’re looking into and I’ll post an update once we believe it should be resolved.

Thanks.

**Comment by oriolpinol** [comment]
@jtanner-msft Thank you very much for your reply and the info provided! Great to hear that you are working on it!

Thanks for your job, keep up the good work!

**Comment by oriolpinol** [comment]
Hi again! @jtanner-msft 
Don't know if it is related to the problems you are solving, but going back to my question on blocking, my connection just got stuck here:

java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

over and over, could that be related to not synchronized access to the callbackList in AMQPSTransport?

Going back to the info you provided in the previous comment, I understand that there might be no need to synchronize for the send itself due to the SocketChannel nature, but all the callback/waitLists should maybe still be synchronized?

Thanks!

**Comment by jtanner-msft** [comment]
Hi Oriolpinol,

  Over the weekend Zoltan checked in a fix for the reconnect socket issue, so I believe that should help to address the socket close problem you were seeing:
https://github.com/Azure/azure-iot-sdks/issues/653 

  Please sync the latest develop branch (and subprojects) to see if that fix has also resolved the problem you were observing.

  If it doesn't please let us know as well.

**Comment by chrit-msft** [comment]
@oriolpinol I will be closing this issue since there was a check-in that should have resolved this behavior.  If you see this behavior return please re-open this issue and reach out immediately.

**Comment by oriolpinol** [comment]
@chrit-msft Hi, I just tested with 1.0.10 and this happened again:

`"qtp166794956-58" #58 prio=5 os_prio=0 tid=0x00007f17154e0800 nid=0x43 runnable [0x00007f16e429e000]
   java.lang.Thread.State: RUNNABLE
        at com.microsoft.azure.iothub.DeviceClient.close(DeviceClient.java:206)
        at se.yanzi.shrek.azureiothub.IoTHubSession.disconnect(IoTHubSession.java:218)
        at se.yanzi.shrek.azureiothub.IoTHubSession.stop(IoTHubSession.java:311)
        at se.yanzi.shrek.plugins.IoTHubPlugin.setState(IoTHubPlugin.java:130)
        at se.yanzi.shrek.plugins.IoTHubPlugin.handleMessage(IoTHubPlugin.java:176)
        at se.yanzi.shrek.plugins.IoTHubPlugin.handleMessage(IoTHubPlugin.java:25)
        at se.yanzi.shrek.cirrus.web.ConfigurationServlet.onMessage(ConfigurationServlet.java:57)
        at se.yanzi.shrek.cirrus.web.WebSocketServletTemplate.onMessage(WebSocketServletTemplate.java:46)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
        at org.eclipse.jetty.websocket.jsr356.annotations.OnMessageTextCallable.call(OnMessageTextCallable.java:63)
        at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callText(JsrEvents.java:197)
        at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextMessage(JsrAnnotatedEventDriver.java:378)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:360)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:367)
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:176)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
        at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)`

It happened when I tried to close the connection to a hub that reached its limit of messages. Maybe related to #645 ?

Thank you for your help
