### ISSUE TITLE
Strong name validation failed. (Exception from HRESULT: 0x8013141A)

### ISSUE THREAD

**Issue by rockthethird** [Azure/azure-iot-sdks#834]
**The following error occurs after a Rebuild Solution.  It disappears after a subsequent Build Solution.**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Loading assembly "C:\Users\*******\.nuget\packages\Microsoft.Azure.Devices\1.0.15\lib\uap10.0\Microsoft.Azure.Devices.Uwp.dll" failed. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Devices.Uwp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'Microsoft.Azure.Devices.Uwp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

The Zone of the assembly that failed was:
MyComputer
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)
   at Microsoft.Build.Tasks.ProcessResourceFiles.ReadAssemblyResources(String name, String outFileOrDir)	Gateway PI

**Comment by arturl** [comment]
Hi @rockthethird,

Thanks for the report. It looks like the UWP assembly is this package is not properly signed. We're working on a fix.

**Comment by jasmineymlo** [comment]
Hi @rockthethird,
I have added the UWP assembly for proper signing in our build script.  It should be fixed in the next release packages.  Thanks.
