### ISSUE TITLE
Done is not a function - Needs improved error reporting for newbies

### ISSUE THREAD

**Issue by sputnick** [Azure/azure-iot-sdks#850]
I was testing the nodejs library using some sample code from Azure documentation and ran into an issue with running a simulated device. Everything was correct with my connection string and the code looked the same as the snippets in the article but I kept getting an error from inside the "azure-iot-device" library. "Done is not a function". After trying all sorts of different connectionstrings (I thought it must be wrong) I dug into the npm module code and figured out that "done" actually was my callback method (duuhhh) and because of stupid copy paste reasons my callback method was really "undefined".  I would suggest catching an "undefined" callback and reporting that in client.js instead of the current stack trace which told me nothing.

node fakedevice.js 

```
Unhandled rejection TypeError: done is not a function
    at /Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device/lib/client.js:234:9
    at /Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/lib/amqp.js:43:7
    at Amqp.<anonymous> (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:111:19)
    at tryCatcher (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/eiki/Documents/development/git-repositories/azure-iot-testing/device/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by pierreca** [comment]
Unfortunately, throwing in case of a missing callback would be an API-breaking change, so we really can't do that. it was an early decision to make callbacks optional. This is still valid in case we find time to implement Promises support in the future. (I'd like to get to a point where I can return a Promise when a callback is undefined and allow both async patterns). 

What we can do however is fix the bug by not trying to call the callback if undefined... which one of the API call was failing?

**Comment by sputnick** [comment]
The api call was just client.open(connectCallback). You don't really have to throw the error up the stack in my view which would break the API like you say. It would be enough to simply log/print that the callback was undefined rather than failing completely with that cryptic message - at least until the method returns a Promise that could pass on the error. This "gotcha" likely only happens to newbies but it's a time waster for sure. Even just renaming the callback parameter from "done" to "callback" would help.

**Comment by tameraw** [comment]
This has been addressed in the develop branch and will be part of our next release (ETA 11/14).
The fix is around renaming the callback argument and not crashing if a callback argument has not been provided.
