### ISSUE TITLE
done is not a function

### ISSUE THREAD

**Issue by MarceloOrbital** [Azure/azure-iot-sdks#865]
Hi,

I'm testing with NodeJS running on a Raspberry PI. Although the device to cloud messages reachs its destination, Node always gives the following error:

`Unhandled rejection TypeError: done is not a function
at /home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/lib/amqp.js:43:7
at /home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:181:21
at tryCatcher (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/promise.js:687:18)
at Async._drainQueue (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/home/pi/orbbus_device_tracker/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/node_modules/amqp10/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues as _onImmediate
at processImmediate as _immediateCallback`

**Comment by pierreca** [comment]
All asynchronous API calls should take a function as last argument. Looks like you're missing a callback somewhere. what does your calling code looks like? 
example to send a message:
```js
client.open(function(err) {
  if (err) console.error('could not open connection');
  else {
    client.sendEvent(msg, function(err) {
      if(err) console.error('message could not be sent');
      else console.log('message sent');
    });
  }
});
```

**Comment by MarceloOrbital** [comment]
@pierreca you are right. I was missing a callback while sending the event.

Thanks
