### ISSUE TITLE
Getting this error when running device identity - TypeError: iothub.Device is not a function

### ISSUE THREAD

**Issue by sankettandulwadkar** [Azure/azure-iot-sdks#956]
Code -

[sanket@sanket-arch-odl createdeviceidentity]$ cat CreateDeviceIdentity.js
var iothub = require('azure-iothub');
var connectionString = "HostName=WtFIoTHub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxx";
var deviceId = "sanketsdevice";

var registry = iothub.Registry.fromConnectionString(connectionString);
var device = new iothub.Device(null);
device.deviceId = deviceId;

registry.create(device, function(err, deviceInfo, res) {
  if (err)
    registry.get(device.deviceId, printDeviceInfo);

  if (deviceInfo)
    printDeviceInfo(err, deviceInfo, res)
});

function printDeviceInfo(err, deviceInfo, res) {
  if (deviceInfo)
    console.log('Generated device key: ' + deviceInfo.authentication.SymmetricKey.primaryKey);
}

npm list - 

[sanket@sanket-arch-odl createdeviceidentity]$ npm list
createdeviceidentity@1.0.0 /home/sanket/azureiot/createdeviceidentity
└─┬ azure-iothub@1.0.19
  ├─┬ azure-iot-amqp-base@1.0.18
  │ ├─┬ amqp10@3.3.2
  │ │ ├─┬ bl@1.1.2
  │ │ │ └─┬ readable-stream@2.0.6
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   ├── inherits@2.0.3
  │ │ │   ├── isarray@1.0.0
  │ │ │   ├── process-nextick-args@1.0.7
  │ │ │   ├── string_decoder@0.10.31
  │ │ │   └── util-deprecate@1.0.2
  │ │ ├── bluebird@3.4.6
  │ │ ├── buffer-builder@0.2.0
  │ │ ├── node-amqp-encoder@0.0.2
  │ │ ├── node-int64@0.4.0
  │ │ └── stately.js@1.3.0
  │ ├─┬ amqp10-transport-ws@0.0.5
  │ │ └── nodejs-websocket@1.7.0
  │ ├─┬ debug@2.3.2
  │ │ └── ms@0.7.2
  │ ├─┬ sinon@1.17.6
  │ │ ├── formatio@1.1.1
  │ │ ├── lolex@1.3.2
  │ │ ├── samsam@1.1.2
  │ │ └─┬ util@0.10.3
  │ │   └── inherits@2.0.1
  │ └─┬ sinon-as-promised@4.0.2
  │   ├─┬ create-thenable@1.0.2
  │   │ ├─┬ object.omit@2.0.1
  │   │ │ ├─┬ for-own@0.1.4
  │   │ │ │ └── for-in@0.1.6
  │   │ │ └── is-extendable@0.1.1
  │   │ └── unique-concat@0.2.2
  │   └── native-promise-only@0.8.1
  ├─┬ azure-iot-common@1.0.17
  │ └── crypto@0.0.3
  ├── azure-iot-http-base@1.0.17
  ├── lodash@4.16.6
  └── uuid@2.0.3

Error -

[sanket@sanket-arch-odl createdeviceidentity]$ node CreateDeviceIdentity.js
/home/sanket/azureiot/createdeviceidentity/CreateDeviceIdentity.js:6
var device = new iothub.Device(null);
             ^

TypeError: iothub.Device is not a function
    at Object.<anonymous> (/home/sanket/azureiot/createdeviceidentity/CreateDeviceIdentity.js:6:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

Can someone please tell me if I am missing something here? I worked fine for another IoT Hub I created. Not working for this one.

Thanks,
Sanket

**Comment by pierreca** [comment]
Looks like we missed the export of the `Device` class in the package for this release. Super easy mitigation while we fix this: instead of trying to instantiate a new `Device` class, just do this:
```js
var device = { deviceId: 'sanketsdevice' };
```

Where did you find this sample code encouraging you to instantiate it that way?

**Comment by sankettandulwadkar** [comment]
Thanks. I just moved back to 1.0.18 and got it working. I will try this change and check again. Thanks for the info.

I believe I got this from one of the websites showing an example. Hard to remember which one, I have been playing with the sample code to get the basic device-to-cloud messages working. 

This is my first issue on one of the devices I am trying to put the client on. And the second issue is that the company I work at, doesn't have port 5671 open by default to run "read device-to-cloud messages" and I am stuck on that part now. I was wondering when the http "event-hub" is coming out. I reckon reading that its in the works. AMQP is great and all, but opening a new port for devices to ship is something a little problematic for us right now. Is there any way to change the protocol to be HTTP to read-device-to-cloud messages?

**Comment by pierreca** [comment]
I'm not sure there's HTTP coming for the Event Hubs side... the folks at https://github.com/azure/azure-event-hubs/ would know. IIRC HTTP simply doesn't scale for the quantity of messages that Event Hubs is supposed to process, and since usually, this is done on the service side, in an Azure-hosted service, so the AMQP port is not really an issue. If that's not the architecture you're going for, these guys definitely need to hear about it, if it's just about unblocking the port, is RDP active? Have you considered spinning up a VM and running the code in the VM on Azure just to unblock the situation?

**Comment by pierreca** [comment]
closing due to inactivity - feel free to reopen if you're still having issues.
