### ISSUE TITLE
Node Device Client SDK stops listening to device method calls when SAS Renewal occurs

### ISSUE THREAD

**Issue by robertwesterlund** [Azure/azure-iot-sdks#966]
When starting a client with the Node Device Client SDK (using the azure-iot-device@1.1.0-dtpreview.2 and azure-iot-device-mqtt@1.1.0-dtpreview.2 npm packages), the client seems to stop listening for device methods when the SAS renewal occurs.

The following code is the relevant parts from the repro attached (complete code, including debug outputs are attached as a zip file):

```
process.on('uncaughtException', function(e){
	console.error('Uncaught exception', e);
	process.exit(-1);
});

const Client = require('azure-iot-device').Client;
const Protocol = require('azure-iot-device-mqtt').Mqtt;
const deviceId = process.argv[2];
const iotHubConnectionString = process.argv[3]; 
const managementConnectionString = process.argv[4];
if (!iotHubConnectionString || !managementConnectionString || !deviceId){
	console.log('Usage: node <jsfile>.js "<deviceid>" "<deviceiothubconnectionstring>" "<managementiothubconnectionstring>"');
	process.exit(0);
}

Client.sasRenewalInterval = 30000;
let client = Client.fromConnectionString(iotHubConnectionString, Protocol);
client.open(function(error){
	setInterval(function(){
		console.log('Probably renewing SAS now');
	}, Client.sasRenewalInterval);
	if (error){
		console.error('Could not connect the client', error);
		process.exit(-2);
	}
	client.onDeviceMethod('ping', function(request, response){
		response.send(200, 'pong', function(error){
			if (error){
				console.error('Failed sending pong answer to the ping method call', error);
			}
		});
	});
});

const ManagementClient = require('azure-iothub').Client;
let managementClient = ManagementClient.fromConnectionString(managementConnectionString);
managementClient.open(function(error) {
	setInterval(function(){
		console.log('Sending ping');
		managementClient.invokeDeviceMethod(deviceId, {
			methodName: 'ping',
			payload: '',
			timeoutInSeconds: 60
		}, function(error, result){
			if (error){
				console.error('Failed calling device method', error);
				process.exit(-4);
			}
			else{
				console.log('Received ' + result.payload);
			}
		});
	}, 5000);
});
```

The `ping` and `pong` will work until the sasRenewalInterval occurs (changing the sasRenewalInterval time changes how long the device method call works) and after the sasRenewalInterval time it will no longer be able to call the device method and it will give an error. The following is the output registered by the attached repro:

```
2016-11-17T13:57:52: Opening client
2016-11-17T13:57:52: Starting to prepare management client side
2016-11-17T13:57:53: Opening management client
2016-11-17T13:57:53: Device client opened
2016-11-17T13:57:53: Management client opened
2016-11-17T13:57:58: Sending ping
2016-11-17T13:57:59: Received pong
2016-11-17T13:58:03: Sending ping
2016-11-17T13:58:04: Received pong
2016-11-17T13:58:08: Sending ping
2016-11-17T13:58:09: Received pong
2016-11-17T13:58:13: Sending ping
2016-11-17T13:58:14: Received pong
2016-11-17T13:58:18: Sending ping
2016-11-17T13:58:19: Received pong
2016-11-17T13:58:23: Probably renewing SAS now
2016-11-17T13:58:23: Sending ping
2016-11-17T13:58:28: Sending ping
2016-11-17T13:58:33: Sending ping
2016-11-17T13:58:38: Sending ping
2016-11-17T13:58:43: Sending ping
2016-11-17T13:58:48: Sending ping
2016-11-17T13:58:53: Probably renewing SAS now
2016-11-17T13:58:53: Sending ping
Failed calling device method { Error
    at new DeviceNotFoundError (C:\git\iot-test\node_modules\azure-iot-common\lib\errors.js:46:17)
    at Function.RestApiClient.translateError (C:\git\iot-test\node_modules\azure-iothub\lib\rest_api_client.js:161:17)
    at C:\git\iot-test\node_modules\azure-iothub\lib\rest_api_client.js:101:28
    at IncomingMessage.onResponseEnd (C:\git\iot-test\node_modules\azure-iot-http-base\lib\http.js:73:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Device not found',
  stack: 'Error\n    at new DeviceNotFoundError (C:\\git\\iot-test\\node_modules\\azure-iot-common\\lib\\errors.js:46:17)\n    at Function.RestApiClient.translateError (C:\\git\\iot-test\\node_modules\\azure-iothub\\lib\\rest_api_client.js:161:17)\n    at C:\\git\\iot-test\\node_modules\\azure-iothub\\lib\\rest_api_client.js:101:28\n    at IncomingMessage.onResponseEnd (C:\\git\\iot-test\\node_modules\\azure-iot-http-base\\lib\\http.js:73:7)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)',
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        error: [Function],
        data: [Function: onResponseData] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '<redacted>',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 541,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 61696,
        read: [Function],
        _consuming: true },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '<redacted>',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 541,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 61696,
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'content-length': '156',
        'content-type': 'application/json; charset=utf-8',
        server: 'Microsoft-HTTPAPI/2.0',
        'iothub-errorcode': 'DeviceNotFound',
        date: 'Thu, 17 Nov 2016 13:58:52 GMT',
        connection: 'close' },
     rawHeaders:
      [ 'Content-Length',
        '156',
        'Content-Type',
        'application/json; charset=utf-8',
        'Server',
        'Microsoft-HTTPAPI/2.0',
        'iothub-errorcode',
        'DeviceNotFound',
        'Date',
        'Thu, 17 Nov 2016 13:58:52 GMT',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '<redacted>',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 541,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 61696,
        read: [Function],
        _consuming: true },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /twins/<redacted>/methods?api-version=2016-09-30-preview HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAuthorization: SharedAccessSignature sr=<redacted>\r\nRequest-Id: 17d8d1f6-f4b8-4b01-8330-cd6647d2bd08\r\nUser-Agent: azure-iothub/1.1.0-dtpreview.2\r\nContent-Length: 56\r\nHost: <redacted>\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/twins/dfd4dabf-2617-46bd-8b2e-e8b9601409ef/methods?api-version=2016-09-30-preview',
        _ended: true,
        timeoutCb: [Function: emitTimeout],
        parser: null,
        res: [Circular] },
     read: [Function] },
  responseBody: '{"Message":"ErrorCode:DeviceNotFound;Device not found","ExceptionMessage":"Tracking ID:032093f651464da199376b643531a96b-G:11-TimeStamp:11/17/2016 13:58:52"}' }
```

[iot-test.zip](https://github.com/Azure/azure-iot-sdks/files/597553/iot-test.zip)

**Comment by markrad** [comment]
Hi @robertwesterlund,

Though it's probably not relevant, but can you tell me on what platform your are running Node.

_Mark Radbourne MSFT_

**Comment by robertwesterlund** [comment]
Sorry for not providing this information right away. I have verified this in Node 6.7.0 on machines with Windows 10 Pro (fully updated).

**Comment by markrad** [comment]
Hi @robertwesterlund,

I have been able to reproduce your issue. I will get back to you after I have done some more research.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @robertwesterlund,

It appears that the "on" functions are cleared during the closure of the MQTT session and not restored afterwards. Currently MQTT does not have the facility for renewing the SAS token in stream. It has to be closed and reopened. I'm passing this off to the product group to fix.

Thank you for informing us of this error and thank you for your excellent sample code.

_Mark Radbourne MSFT_

**Comment by BertKleewein** [comment]
I have a fix prepared and I am reviewing it with my colleagues.  I hope to get it committed shortly.

**Comment by BertKleewein** [comment]
This has been fixed in the azure-iot-sdk-node repo develop branch with the following commit: 

[https://github.com/Azure/azure-iot-sdk-node/commit/2f2237e597ef3b7869f28c0f2e5aa65f0201d032]
