### ISSUE TITLE
[Java] DeviceClient creates a "cert.crt" file 

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#995]
I noticed a `cert.crt` file continuously appearing in the root of a project using `com.microsoft.azure.iothub.DeviceClient`. Is it possible to fix the SDK, so that the library doesn't write to the filesystem?

```
import com.microsoft.azure.iothub.DeviceClient;
import com.microsoft.azure.iothub.IotHubClientProtocol;

public class TestDeviceClient
{
    static String hub = System.getenv("SDK_HUB_NAME");
    static String device = System.getenv("SDK_DEVICE_ID");
    static String deviceKey = System.getenv("SDK_DEVICE_KEY");

    public static void main(String[] args) throws Exception
    {
        String cs = "HostName=" + hub + ".azure-devices.net;DeviceId=" + device + ";SharedAccessKey=" + deviceKey;
        DeviceClient client = new DeviceClient(cs, IotHubClientProtocol.AMQPS);
        client.open();
        client.close();
    }
}
```

`cert.crt`:

```
-----BEGIN CERTIFICATE-----
MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD
VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX
DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y
...cut...
-----END CERTIFICATE-----
```

**Comment by zolvarga** [comment]
Hi dluc,

Our Java SDKs use Proton-j library for AMQP connection. Proton-J only accepts file path for certificate and it does not work with certificate stored in a variable. That is why we need to store the certificate in file. 
Note: If you use SetOption you can have control on the path where you store your own certificate.

Best Regards,
Zoltan

**Comment by dluc** [comment]
Hi Zoltan,

the authentication is based on SharedAccessKey, I don't have any certificate in the device.

I think this is a bug, otherwise the application should throw some exception, right?

Also, a device storage is most probably read-only, if the code attempts to write to storage, this would fail.
 
Thanks
Devis

**Comment by dluc** [comment]
Hi Zoltan,

the authentication is based on SharedAccessKey, there is no certificate in the device.

I think this is a bug, otherwise the application should throw some exception, right?

Also, a device storage is most probably read-only, if the code attempts to write to storage, creating a file will cause a fatal error.
 
Thanks
Devis

**Comment by dluc** [comment]
For reference, the issue affects only DeviceClient. 

The following code using ServiceClient, doesn't create any file:

```
import com.microsoft.azure.iot.service.sdk.IotHubServiceClientProtocol;
import com.microsoft.azure.iot.service.sdk.ServiceClient;

public class TestServiceClient
{
    static String hub = System.getenv("SDK_HUB_NAME");
    static String serviceKey = System.getenv("SDK_SERVICE_KEY");

    public static void main(String[] args) throws Exception
    {
        String cs = "HostName=" + hub + ".azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=" + serviceKey;
        ServiceClient client = ServiceClient.createFromConnectionString(cs, IotHubServiceClientProtocol.AMQPS);
        client.open();
        client.close();
    }
}
```

**Comment by olivierbloch** [comment]
Reopening as this seems like an issues we need to investigate considering the service client SDK doesn't have the same behavior while still establishing an AMQP connection with IoT Hub using ProtonJ

**Comment by dluc** [comment]
FYI this issue is crashing a multithreaded application. For instance I have an integration test instantiating multiple device clients - the test fails because the DeviceClient instances are competing to create/recreate/write this file, leading to this fatal exception:

```
Nov 29, 2016 8:57:51 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory readCertificate
SEVERE: Failed to load certificate [/workspace/cert.crt]
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Incomplete data
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:110)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory.readCertificate(SslEngineFacadeFactory.java:433)
	at org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory.createKeyStoreFrom(SslEngineFacadeFactory.java:335)
	at org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory.getOrCreateSslContext(SslEngineFacadeFactory.java:280)
	at org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory.createAndInitialiseSslEngine(SslEngineFacadeFactory.java:207)
	at org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFactory.createProtonSslEngine(SslEngineFacadeFactory.java:184)
	at org.apache.qpid.proton.engine.impl.ssl.SslDomainImpl.createSslEngine(SslDomainImpl.java:132)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.initTransportWrapperOnFirstIO(SslImpl.java:231)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.capacity(SslImpl.java:108)
	at org.apache.qpid.proton.engine.impl.TransportImpl.capacity(TransportImpl.java:1428)
	at org.apache.qpid.proton.reactor.impl.IOHandler.capacity(IOHandler.java:172)
	at org.apache.qpid.proton.reactor.impl.IOHandler.update(IOHandler.java:204)
	at org.apache.qpid.proton.reactor.impl.IOHandler.selectableTransport(IOHandler.java:329)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleBound(IOHandler.java:166)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:372)
	at org.apache.qpid.proton.engine.BaseHandler.onConnectionBound(BaseHandler.java:58)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.iothub.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:861)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Incomplete data
	at sun.security.provider.X509Factory.readOneBlock(X509Factory.java:612)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:96)
	... 26 more
```

**Comment by prmathur-microsoft** [comment]
1. Currently Peer verification is only supported for device client. Service client doesn't have that feature and it is on our backlog to implement it.
2. You are right about the bug on multi threaded application. We need to have a fix a to guard it for multi threading for multiple devices.
3. We have a setoption for cases where user can specify a suitable path for the certificate in which case we will not create this cert and instead use the path specified by user.

**Comment by anhashia** [comment]
Linking to  https://github.com/Azure/azure-iot-sdks/issues/986

**Comment by jtanner-msft** [comment]
Discussed with @prmathur-microsoft and she'll pursue getting #2 in the list above added.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#19
